### PR TITLE
replacing instances of "products" and "software" with "ICT"

### PR DESCRIPTION
**Pull request by nitedog**
The section uses the term "closed functionality products" and later on "closed functionality software", and most of the time the keywords "products" and "software" can be either dropped or replaced by "ICT".

### CODE REVIEW

**Comment by GreggVan** [comment]
I actually thing that this needs to be.  ICT with closed functionality.    

All the rules apply to the functionality that is closed — not the product.    If a product is only closed to some assistive technologies.  (As the iPhone is, which allows alternate keyboard AT) then the product only has to provide alternate functionality for the AT that it is closed to. 

This keeps getting overlooked and things seem to often be written like closed is an all or nothing proposition for products. 

(Many kiosks for example have headphone jacks that allow all sorts of audio AT to be used)

Thx
g

**Comment by nitedog** [comment]
I agree @GreggVan and tried to reflect that in my suggested edits. You can see the changes I'm proposing at this link: https://github.com/w3c/wcag2ict/pull/256/files

**Comment by mraccess77** [comment]
The first Section 508 said that “Personal headsets for private listening are not assistive technology.”

The revised 508 standards say “ICT with closed functionality shall be operable without requiring the user to attach or install assistive technology other than personal headsets or other audio couplers, and shall conform to…”

So, I generally do not consider headsets assistive technology.

**Comment by GreggVan** [comment]
That I just a dodge that will come back to haunt us.     Neck loops and audio amplifiers are absolutely assistive technologies.   We just said they weren’t AT because we had trouble calling kiosks and such closed products when they would work with AT connected through there headphone jacks.

Instead we have found that we had to (for other reasons) dump the ‘closed products’ language and move to closed functionality.   If we had done that in the first place - we would not have had to invent the "things plugged into the headphone. Jack are not AT” dodge.

(For anyone with a hearing impairment - headphones as well as anything else plugged into a headphone jack are AT.
Even for people who are blind — they are AT for privacy reasons.  


Now that we have the “closed fungtionality” approach — we no longer have to use the dodge —so I think we should drop that. 


Best
G

**Comment by mraccess77** [comment]
So it seems like a keyboard, mouse, or an external monitor could be considered assistive technology.  This understanding could have an impact on testing accommodations for test takers with disabilities as these things would need to be approved accommodations because they are assistive technology.

**Comment by samogami** [comment]
I would change "something else" to alternatives and shorten the sentence. 
> "Where assistive technologies or user agents are not available to address the intent of these success criteria, alternatives should be provided."

**Comment by bruce-usab** [comment]
I am optimistic that WCAG2ICT can avoid having to address if headsets are AT (or not).

Headsets meet most definitions for AT.  It was awkward how the original 508 asserted 
>Personal headsets for private listening are not assistive technology.

The revised uses the more nuanced phrasing as @mraccess77 points out:
> ICT with closed functionality shall be operable without requiring the user to attach or install assistive technology other than personal headsets or other audio couplers.

As some background... People who rely upon ATMs (and the like) being <q>speech output enabled</q> have gotten into the habit of carrying ear buds (or neckloops, or amplified noise-cancelling headphones), and only requiring the audio jack has been effective.  Nowadays, the speech output mode starts automatically when a 1/8&quot; plug is inserted.  This behavior was industry's clever idea, not something regulators thought of!

**Comment by GreggVan** [comment]
Ah.  We have two mixed topics here.

1) are earbuds/headphones AT
If you are referring to earbuds/headphones as not being AT — I agree.
Anyone can use a standard device as an assistive technology. 
But in this case we are talking about devices made specifically for people with disabilities.
So while earbuds may be used as an AT,  amplifiers and neck loops that plug into a kiosk are.

2) are kiosks “closed products” or only products with closed functionality?
Or 
Are kiosks closed to all AT?

Here, kiosks with headphone jacks are not closed to all AT because amplifiers and neck loops plug into headphone jacks and are AT

So they have a LOT of closed functionality to many disabilities — and would need to address the role that AT can provide in making the product accessible IF their functionality were not closed. 


PS Technology is coming, and is already here today in prototype research prototype form, of T is, that will allow blind people to use touchscreen kiosks without any built-in accommodations for the person who is blind. They can simply attach a small device to the screen, which reads the screen, provides a text and speech interface to the contents, and has a small actuator that will touch the screen in the right places when someone makes a choice on the alternate presentation of the screens content. These are a bit limited in the types of interfaces they can handle today, but more advanced versions will be coming. See also the presentation on Info-Bot and Individual User Interface Generators (IUIGs) <https://futureofinterface.org/auditorium_cpt/alternate-visions-for-accessibility-in-future/>

**Comment by maryjom** [comment]
Closing this PR, as I made other edits in my original PR based on your input and the survey input. This caused some more major edits affecting the text you modified. See PR# #254.

**Pull request closed without merging**
