### PR TITLE
ISO refs

### LINKED ISSUE #390: Need update non-normative references to EN and ISO standards
EN 301 549 is at a newer version:

[ETSI EN 301 549 V3.2.1 (2021-03): Accessibility requirements for ICT products and services](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf). ETSI. March 2021. Published. URL: [https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf)

We also need references for two ISO standards that will enable us to reference them from the definition of "platform software":
ISO 9241-171:2008 
[Ergonomics of human-system interaction Part 171: Guidance on software accessibility](https://www.iso.org/standard/39080.html). International Standards Organization. URL: https://www.iso.org/standard/39080.html

ISO/IEC 13066-1:2011
[Information technology - Interoperability with assistive technology (AT) Part 1: Requirements and recommendations for interoperability](https://www.iso.org/standard/53770.html). International Standards Organization. URL: https://www.iso.org/standard/53770.html

### PR DESCRIPTION
**Pull request by daniel-montalvo**
- Closes #390

### CODE REVIEW

**Review by ChrisLoiselle — APPROVED** [review]

**Review by maryjom — CHANGES_REQUESTED** [review]
This issue also talked about a needed update to the EN 301 549 reference. This reference does not originate from a specific WCAG2ICT and I'm not sure where it comes from to generate the appropriate update.

EN 301 549 is at a newer version:

[ETSI EN 301 549 V3.2.1 (2021-03): Accessibility requirements for ICT products and services](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf). ETSI. March 2021. Published. URL: [https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf](https://www.etsi.org/deliver/etsi_en/301500_301599/301549/02.01.02_60/en_301549v020102p.pdf)

**Comment by GreggVan** [comment]
since there is a new one under development -- I  think this general link that will take you to the latest might be a better  "evergreen" link 

https://www.etsi.org/standards#page=1&search=EN%20301%20549

it is slow to load but it will give you latest version at whatever point in time you click on it.

**Comment by maryjom** [comment]
Just realized, the EN link was updated (must have been on a different PR) and shows in the built document. @GreggVan I think references need to be to a specific version - @daniel-montalvo correct me if I'm wrong on that.

**Review by maryjom — APPROVED** [review]

**Comment by daniel-montalvo** [comment]
@GreggVan @maryjom 
this is not something we manage directly here.

Relevan update happened at tobie/specref#790

Our document will pull any updates that the ETSI people want to make to spec ref

I think the best place to discuss how specref should handle ETSI documents is https://github.com/tobie/specref

**Comment by GreggVan** [comment]
If you are a normative document and you want to cite another normative standard normatively,  then you need to state the specific standard and date you are referring to.   (you can't cite something normatively that might change).

But for informative references to another document or effort -- people are generally interested in seeing the latest version.   And, since they are dated, they can also check to see which version was in effect when your paper or note or whatever was released.    

in this case -- you are talking about how this (WCAG2ICT) document might be used.  it clearly won't be used for an already existing EN 301 549 -- but rather for a future one  (like the one under development now).

**Pull request merged**
