### PR TITLE
Proposed updates relating to text terminal and CLI applications. Two MD files are edited.

### PR DESCRIPTION
**Pull request by JaninaSajka**

### CODE REVIEW

**Comment by mitchellevan** [comment]
In the "background" file, a phrase that was already there in the prior version:

> Alternately, a text application screen reader might directly consume the output rendered (perhaps by acting as its own terminal application or by analyzing the “TTY” output).

Does "might" mean some actually do? What's an example? If "might" was speculation for a possible future, and it hasn't actually happened in the intervening years, I propose we remove such speculations.

In the "text-command-line" file, another phrase that was already there:

> ... command-line applications are a subset of text applications with further specific properties.

This is vague in two ways. First, it's vague whether it's saying the present does or does not address the superset. Second, it doesn't even give an example of what it's referring to. I propose we clarify this phrase significantly, or otherwise remove it. 

One of @JaninaSajka's edits:

> ASR-based voice input 

Please spell out ASR.

**Comment by mraccess77** [comment]
I agree that this "Because assistive technologies developed analysis techniques to recognize many forms of tabular layout, column headers, and section headings, such recognized layouts are by definition “accessibility supported”. Where assistive technology is able to extract and present that information, it is “programmatically determinable”—even though no explicit markup or API was used to make it so." is a pretty bold assertion and would need to be backed up to be usable otherwise it carves out a large whole in WCAG.

**Comment by maryjom** [comment]
The edits to the following statement reads a little awkwardly, as it has "further" in the sentence twice:
>We note further that command-line applications are a subset of text applications with further specific properties.

Suggest that this be edited to say:
>Command-line applications are a subset of text applications with some specific properties.

Should the specific properties be denoted with "such as, list a couple of unique things."

**Comment by maryjom** [comment]
Editorial to add commas: 
>In fact, command-line interfaces have seen a resurgence in recent years especially in popular programming and revision tracking environments. In some cases, this has precipitated renewed developments in assistive technology support for text applications.

Beyond that, it seems that we may need to revisit this text after we've completed our SC by SC analysis to expand on "programmatically determined" and the fact that it isn't always available in such an environment, or is available only through special character-based formatting rather than programmatically in the traditional platform-based API sense.

**Comment by maryjom** [comment]
Regarding @mitchellevan's first comment regarding evaluators and answering the concern in the present document (quoted below from his comment):

> 
> That said, evaluators (including me) would benefit from knowing what these analysis techniques are and how to turn them on when evaluating a text-based interface. Otherwise we'll either pass everything in text (because this part of WCAG2ICT seems to shift the burden rather strongly onto the user agents) or fail too much (because we couldn't observe it working in a user agent, not knowing which one to use or how to configure it).
> 
> Can we answer this concern in the present documents? If not, then where?

I don't think WCAG2ICT can make comment on testing techniques and guidance, as our scope doesn't permit us to come up with techniques. Just like we don't make comment on how specific document types can or cannot meet WCAG SC. We can make comment on the fact that programmatic information is not through APIs, and implications of that. e.g. the SC with programmatic relationship and information requirements would need guidance or some alternative requirement that would have to be developed outside of WCAG2ICT. WCAG2ICT can document which SC are the problematic ones -just like the appendix on applying WCAG to non-web software on closed functionality products.  I am hoping that our SC analysis can bring us some good conclusions on what could be said in the context of WCAG2ICT. There would likely be other standardization or guidance work needed to point out what is possible/feasible to make text/CLI/Terminal emulation applications and the content they output accessible and potentially what test techniques should be utilized.

**Comment by matatk** [comment]
Just a nit. I suggest a slight re-phrasing as follows. Instead of:

> In fact command-line interfaces have seen a resurgence in recent years especially in popular programming and revision tracking environments.

Can we have:

> In fact command-line interfaces have seen a resurgence, in recent years especially in popular programming environments and revision tracking tools.

Rationale: generally people see revision trackers as tools. Note also the added comma after "resurgence" to impart a pause (I think this aligns with @maryjom's suggestion above).

**Comment by maryjom** [comment]
@JaninaSajka I've completed incorporating the editorial changes from Matt, Mitch and myself.

**Pull request merged**
