### PR TITLE
Script includes

### PR DESCRIPTION
**Pull request by michael-n-cooper**
This is probably not previewable in its current form, but I've got the basic wiring to include WCAG 2 content in WCAG2ICT. Hopefully it's mainly tweaking from here. I have to make the JSON file available elsewhere, which is what breaks preview for the moment.

### CODE REVIEW

**Comment by michael-n-cooper** [comment]
[Preview](https://raw.githack.com/w3c/wcag2ict/script-includes/index.html)

**Comment by michael-n-cooper** [comment]
This script is adding WCAG quotes for principles, guidelines, and SC. There are other things to add, and maybe formatting, but getting this basic functionality in should help things along.

**Review by daniel-montalvo — APPROVED** [review]
Thanks much @michael-n-cooper

**Comment by maryjom** [comment]
@michael-n-cooper I've merged, but don't know how to see an editor's draft where the script has run and included the content. The preview link you have included in your comment above doesn't have the latest markdown file changes.

**Pull request merged**
