### PR TITLE
Add SC 1.3.5 to the document

### PR DESCRIPTION
**Pull request by ChrisLoiselle**
@maryjom removed # Success Criteria Problematic for Closed Functionality section (https://w3c.github.io/wcag2ict/#success-criteria-problematic-for-closed-functionality)

- 1.3.5 Identify Input Purpose https://www.w3.org/TR/WCAG22/#identify-input-purpose requires information in a programmatically determinable form. from this file and put into closed functionality md file.

### CODE REVIEW

**Comment by maryjom** [comment]
@ChrisLoiselle Take a look at the commits I made to fix formatting and add the statement to the closed functionality section. I think this takes care of all of my comments and viewing the commits will help you see the formatting I think will be needed at this point. We'll see if there are future Respec/include cleanups needed in the future.  This should handle all changes needed for [Issue #66] and its parent [Issue #25].

**Review by ChrisLoiselle — COMMENTED** [review]
Thanks!

**Review by ChrisLoiselle — COMMENTED** [review]
Thanks!

**Review by ChrisLoiselle — COMMENTED** [review]
Thanks!

**Review by ChrisLoiselle — COMMENTED** [review]
Thanks!

**Review by ChrisLoiselle — COMMENTED** [review]
Thank you!

**Pull request merged**
