### PR TITLE
Add 3.2.6 to list of "set of" criteria and clarify sentence

### PR DESCRIPTION
**Pull request by maryjom**
See issue #283.

### CODE REVIEW

**Comment by maryjom** [comment]
@mitchellevan Please review this PR to make sure it satisfies your concern in issue 283. Thanks!

**Review by pday1 — CHANGES_REQUESTED** [review]
Typos in second sentence:

 Therefore, for in the WCAG2ICT guidance for the provisions that use the phrase “set of” (success criteria 2.4.1, 2.4.5, 3.2.3, 3.2.4, and 3.2.6), the phrase “set of software programs” is used.</div>

Suggested change: 
Therefore, in the WCAG2ICT guidance for the provisions that use the phrase “set of” (success criteria 2.4.1, 2.4.5, 3.2.3, 3.2.4, and 3.2.6), the phrase “set of software programs” is used.</div>

**Comment by maryjom** [comment]
@pday1 Thanks for catching. Have updated and the PR needs re-review.

**Review by pday1 — APPROVED** [review]

**Comment by maryjom** [comment]
Closing, as this change has been made and merged.

**Pull request merged**
