### PR TITLE
Target-size-minimum updates for WCAG2ICT

### PR DESCRIPTION
**Pull request by ChrisLoiselle**
Target-size-minimum updates for WCAG2ICT

### CODE REVIEW

**Review by pday1 — DISMISSED** [review]
The richdiff preview seemed to show some formatting errors in the titles for non-web software and documents - were these meant to be titles?

Similarly, I'm not sure if we need the additional word NOTE after creating a note div.
Then again, I'm definitely not an expert so may be wrong on all these points!

**Review by maryjom — APPROVED** [review]
Approve with the changes I made.

**Comment by maryjom** [comment]
@daniel-montalvo Could you please review this? Phil is out for a week, and I made additional changes that need reviewing before I can merge.

**Review by maryjom — APPROVED** [review]

**Comment by maryjom** [comment]
@pday1 I addressed the issue you brought up, so dismissed your review to try to get this merged.

**Pull request merged**
